### ISSUE TITLE
关于uncased_L-12_H-768_A-12/vocab.txt 没有文件

### ISSUE THREAD

**Issue by lijhong** [1429904852/R-GCN#1]
作者你好，我最近看到你这篇论文的想法很有趣，想运行下你的实验程序，但是报错提示uncased_L-12_H-768_A-12/vocab.txt 没有文件，不知道这个文件是怎么生成的？想请教下能否提供下相关文件或者生成这个文件的方法，非常感谢！

**Comment by 1429904852** [comment]
感谢对我们工作的关注，uncased_L-12_H-768_A-12文件夹太大了，我将它放在了百度网盘（readme文件提供了网盘链接），具体的链接如下：
https://pan.baidu.com/s/1wMj5v0xpPgMSjqaymmuJrw?pwd=9ArR
