### ISSUE TITLE
关于twitter2017中没有twitter2017_images压缩包

### ISSUE THREAD

**Issue by M1natoAqua** [1429904852/R-GCN#2]
最近有幸拜读您的论文让我产生了非常大的兴趣，于是准备实验跑跑看，但是我发现在您提供的百度云盘里twitter2017的数据集中缺少了twitter2017_images压缩包，不知道您是否方便提供一下？万分抱歉打扰到您，祝顺利！

**Comment by grandchicken** [comment]
非常抱歉给您带来不便，更新的压缩包见此链接https://drive.google.com/file/d/1EGgCJ4HfsMuW4OF-1TnCbLXUkKwYD1YG/view?usp=sharing

**Comment by M1natoAqua** [comment]
十分感谢您！之后我实际复现了您的实验，在twitter2015数据集上跑出了和您论文十分相近的结果，这也说明你们的模型效果非常好。但是在twitter2017数据集上train的时候遇到了一些问题，在读取images2017_feature后，读取img2text_sim_topk_vec_2017时出现了错误，具体报错如下：
index transform finished
label index transform finished
pictures_id
(3373, 49, 2048)
Traceback (most recent call last):
  File "trainer.py", line 135, in <module>
    trainer = Trainer(args)
  File "trainer.py", line 23, in __init__
    self.data_obj.gen_data(self.config["train_data"])
  File "E:\JTH\R-GCN-main\data_helper.py", line 187, in gen_data
    pt_image_id = self.picture_feature(pt_image, self.__pt_pictures_path)
  File "E:\JTH\R-GCN-main\data_helper.py", line 111, in picture_feature
    photo_features = np.load(photo_feature_path)
  File "E:\conda\envs\RGCN\lib\site-packages\numpy\lib\npyio.py", line 440, in load
    pickle_kwargs=pickle_kwargs)
  File "E:\conda\envs\RGCN\lib\site-packages\numpy\lib\format.py", line 771, in read_array
    array.shape = shape
ValueError: cannot reshape array of size 172468 into shape (5,49,2048)

不知道您是否可以为我指点迷津？真的十分感您！

**Comment by M1natoAqua** [comment]
您好，我目前成功在两个数据集上跑出来了你们论文的效果，但是twitter2017的4条数据是有问题的，具体是下面这4条：
data/twitter2017/img2text_sim_topk_vec_2017/k_5/17_06_7116##17_06_7687##17_06_3037##16_05_27_52##16_05_01_107.npy
data/twitter2017/img2text_sim_topk_vec_2017/k_5/17_06_7116##17_06_7549##16_05_10_801##17_06_7093##16_05_13_78.npy
data/twitter2017/img2text_sim_topk_vec_2017/k_5/17_06_7116##17_06_7093##16_05_29_387##17_06_12677##16_05_05_1113.npy
data/twitter2017/img2text_sim_topk_vec_2017/k_5/17_06_7116##17_06_12677##16_05_05_1113##17_06_6687##16_05_23_81.npy

这4条数据不知道是在传输或压缩的哪个部分可能有损坏，表现在维度不一致报错。不知道您是否能重新提供下这4个npy文件？万分感谢！

**Comment by 1429904852** [comment]
好的，这个数据有点久远了，我得找一下，找到了我更新一下，谢谢您的反馈。

**Comment by M1natoAqua** [comment]
好的，也麻烦您了，十分感谢您这么晚了还能回复我，祝您顺利！



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年9月6日(周三) 凌晨0:05
收件人: ***@***.***&gt;;
抄送: "Jiang ***@***.******@***.***&gt;;
主题: Re: [1429904852/R-GCN] 关于twitter2017中没有twitter2017_images压缩包 (Issue #2)




 
好的，这个数据有点久远了，我得找一下，找到了我更新一下，谢谢您的反馈。

**Comment by lanadelray12** [comment]
> 您好，我目前成功在两个数据集上跑出来了你们论文的效果，但是twitter2017的4条数据是有问题的，具体是下面这4条： data/twitter2017/img2text_sim_topk_vec_2017/k_5/17_06_7116##17_06_7687##17_06_3037##16_05_27_52##16_05_01_107.npy data/twitter2017/img2text_sim_topk_vec_2017/k_5/17_06_7116##17_06_7549##16_05_10_801##17_06_7093##16_05_13_78.npy data/twitter2017/img2text_sim_topk_vec_2017/k_5/17_06_7116##17_06_7093##16_05_29_387##17_06_12677##16_05_05_1113.npy data/twitter2017/img2text_sim_topk_vec_2017/k_5/17_06_7116##17_06_12677##16_05_05_1113##17_06_6687##16_05_23_81.npy
> 
> 这4条数据不知道是在传输或压缩的哪个部分可能有损坏，表现在维度不一致报错。不知道您是否能重新提供下这4个npy文件？万分感谢！



> 您好，我目前成功在两个数据集上跑出来了你们论文的效果，但是twitter2017的4条数据是有问题的，具体是下面这4条： data/twitter2017/img2text_sim_topk_vec_2017/k_5/17_06_7116##17_06_7687##17_06_3037##16_05_27_52##16_05_01_107.npy data/twitter2017/img2text_sim_topk_vec_2017/k_5/17_06_7116##17_06_7549##16_05_10_801##17_06_7093##16_05_13_78.npy data/twitter2017/img2text_sim_topk_vec_2017/k_5/17_06_7116##17_06_7093##16_05_29_387##17_06_12677##16_05_05_1113.npy data/twitter2017/img2text_sim_topk_vec_2017/k_5/17_06_7116##17_06_12677##16_05_05_1113##17_06_6687##16_05_23_81.npy
> 你好我在先在tw2015上跑了实验，但是结果与作者论文中的结果还有一点点
的差距，请问是需要调参吗> 这4条数据不知道是在传输或压缩的哪个部分可能有损坏，表现在维度不一致报错。不知道您是否能重新提供下这4个npy文件？万分感谢！

**Comment by lanadelray12** [comment]
> 您好，我目前成功在两个数据集上跑出来了你们论文的效果，但是twitter2017的4条数据是有问题的，具体是下面这4条： data/twitter2017/img2text_sim_topk_vec_2017/k_5/17_06_7116##17_06_7687##17_06_3037##16_05_27_52##16_05_01_107.npy data/twitter2017/img2text_sim_topk_vec_2017/k_5/17_06_7116##17_06_7549##16_05_10_801##17_06_7093##16_05_13_78.npy data/twitter2017/img2text_sim_topk_vec_2017/k_5/17_06_7116##17_06_7093##16_05_29_387##17_06_12677##16_05_05_1113.npy data/twitter2017/img2text_sim_topk_vec_2017/k_5/17_06_7116##17_06_12677##16_05_05_1113##17_06_6687##16_05_23_81.npy
> 
> 这4条数据不知道是在传输或压缩的哪个部分可能有损坏，表现在维度不一致报错。不知道您是否能重新提供下这4个npy文件？万分感谢！

你好我在先在tw2015上跑了实验，但是结果与作者论文中的结果还有一点点的差距，请问是需要调参吗

**Comment by M1natoAqua** [comment]
> > 您好，我目前成功在两个数据集上跑出来了你们论文的效果，但是twitter2017的4条数据是有问题的，具体是下面这4条： data/twitter2017/img2text_sim_topk_vec_2017/k_5/17_06_7116##17_06_7687##17_06_3037##16_05_27_52##16_05_01_107.npy data/twitter2017/img2text_sim_topk_vec_2017/k_5/17_06_7116##17_06_7549##16_05_10_801##17_06_7093##16_05_13_78.npy data/twitter2017/img2text_sim_topk_vec_2017/k_5/17_06_7116##17_06_7093##16_05_29_387##17_06_12677##16_05_05_1113.npy data/twitter2017/img2text_sim_topk_vec_2017/k_5/17_06_7116##17_06_12677##16_05_05_1113##17_06_6687##16_05_23_81.npy
> > 这4条数据不知道是在传输或压缩的哪个部分可能有损坏，表现在维度不一致报错。不知道您是否能重新提供下这4个npy文件？万分感谢！
> 
> 你好我在先在tw2015上跑了实验，但是结果与作者论文中的结果还有一点点的差距，请问是需要调参吗

有一点波动是很正常的，配置不同也会造成实验结果不同，可以通过调参来解决

**Comment by lanadelray12** [comment]
> > > 您好，我目前成功在两个数据集上跑出来了你们论文的效果，但是twitter2017的4条数据是有问题的，具体是下面这4条： data/twitter2017/img2text_sim_topk_vec_2017/k_5/17_06_7116##17_06_7687##17_06_3037##16_05_27_52##16_05_01_107.npy data/twitter2017/img2text_sim_topk_vec_2017/k_5/17_06_7116##17_06_7549##16_05_10_801##17_06_7093##16_05_13_78.npy data/twitter2017/img2text_sim_topk_vec_2017/k_5/17_06_7116##17_06_7093##16_05_29_387##17_06_12677##16_05_05_1113.npy data/twitter2017/img2text_sim_topk_vec_2017/k_5/17_06_7116##17_06_12677##16_05_05_1113##17_06_6687##16_05_23_81.npy
> > > 这4条数据不知道是在传输或压缩的哪个部分可能有损坏，表现在维度不一致报错。不知道您是否能重新提供下这4个npy文件？万分感谢！
> > 
> > 
> > 你好我在先在tw2015上跑了实验，但是结果与作者论文中的结果还有一点点的差距，请问是需要调参吗
> 
> 有一点波动是很正常的，配置不同也会造成实验结果不同，可以通过调参来解决
跑2017数据集的时候，遇到了一个问题不知道你有没有遇到过呢：ValueError: cannot reshape array of size 172468 into shape (5,49,2048)
好像是是numpy进行reshape操作出现了问题

**Comment by M1natoAqua** [comment]
> > > > 您好，我目前成功在两个数据集上跑出来了你们论文的效果，但是twitter2017的4条数据是有问题的，具体是下面这4条： data/twitter2017/img2text_sim_topk_vec_2017/k_5/17_06_7116##17_06_7687##17_06_3037##16_05_27_52##16_05_01_107.npy data/twitter2017/img2text_sim_topk_vec_2017/k_5/17_06_7116##17_06_7549##16_05_10_801##17_06_7093##16_05_13_78.npy data/twitter2017/img2text_sim_topk_vec_2017/k_5/17_06_7116##17_06_7093##16_05_29_387##17_06_12677##16_05_05_1113.npy data/twitter2017/img2text_sim_topk_vec_2017/k_5/17_06_7116##17_06_12677##16_05_05_1113##17_06_6687##16_05_23_81.npy
> > > > 这4条数据不知道是在传输或压缩的哪个部分可能有损坏，表现在维度不一致报错。不知道您是否能重新提供下这4个npy文件？万分感谢！
> > > 
> > > 
> > > 你好我在先在tw2015上跑了实验，但是结果与作者论文中的结果还有一点点的差距，请问是需要调参吗
> > 
> > 
> > 有一点波动是很正常的，配置不同也会造成实验结果不同，可以通过调参来解决
> > 跑2017数据集的时候，遇到了一个问题不知道你有没有遇到过呢：ValueError: cannot reshape array of size 172468 into shape (5,49,2048)
> > 好像是是numpy进行reshape操作出现了问题

这个问题就是我提到的，你可以跳过我上面列出的4个npy，这样就可以了

**Comment by lanadelray12** [comment]
好的好的，万分感谢

**Comment by lanadelray12** [comment]
> > > > > 您好，我目前成功在两个数据集上跑出来了你们论文的效果，但是twitter2017的4条数据是有问题的，具体是下面这4条： data/twitter2017/img2text_sim_topk_vec_2017/k_5/17_06_7116##17_06_7687##17_06_3037##16_05_27_52##16_05_01_107.npy data/twitter2017/img2text_sim_topk_vec_2017/k_5/17_06_7116##17_06_7549##16_05_10_801##17_06_7093##16_05_13_78.npy data/twitter2017/img2text_sim_topk_vec_2017/k_5/17_06_7116##17_06_7093##16_05_29_387##17_06_12677##16_05_05_1113.npy data/twitter2017/img2text_sim_topk_vec_2017/k_5/17_06_7116##17_06_12677##16_05_05_1113##17_06_6687##16_05_23_81.npy
> > > > > 这4条数据不知道是在传输或压缩的哪个部分可能有损坏，表现在维度不一致报错。不知道您是否能重新提供下这4个npy文件？万分感谢！
> > > > 
> > > > 
> > > > 你好我在先在tw2015上跑了实验，但是结果与作者论文中的结果还有一点点的差距，请问是需要调参吗
> > > 
> > > 
> > > 有一点波动是很正常的，配置不同也会造成实验结果不同，可以通过调参来解决
> > > 跑2017数据集的时候，遇到了一个问题不知道你有没有遇到过呢：ValueError: cannot reshape array of size 172468 into shape (5,49,2048)
> > > 好像是是numpy进行reshape操作出现了问题
> 
> 这个问题就是我提到的，你可以跳过我上面列出的4个npy，这样就可以了

这个要怎么跳过呀

**Comment by lanadelray12** [comment]
解决了哈哈

**Comment by DanWu2003** [comment]
打扰了，想问问实验能在Tensorflow2.x版本上跑吗？由于我的显卡是RTX 3090，只能使用11.0版本以上的cuda，因此不能安装Tensorflow1.x。我是用Tensorflow2.4版本，并将报错的代码迁移到2.x用法上，但是运行结果recall: 0, precision: 0, f1: 0。请问你们有什么建议吗？

**Comment by 1429904852** [comment]
> 打扰了，想问问实验能在Tensorflow2.x版本上跑吗？由于我的显卡是RTX 3090，只能使用11.0版本以上的cuda，因此不能安装Tensorflow1.x。我是用Tensorflow2.4版本，并将报错的代码迁移到2.x用法上，但是运行结果recall: 0, precision: 0, f1: 0。请问你们有什么建议吗？

代码在1.x的版本上实现的，2.0的tf版本可能不兼容
